baseurl = "https://kurtschneider0.github.io/"
languageCode = "en-us"
title = "Kurt Schneider"
theme="archie"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate=3 # articles per page

[params]
	mode="toggle" # color-mode â†’ light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "My blog about math, programming and other stuff"

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/kurtschneider0"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
